# Generated by Django 6.0.7 on 2026-08-18 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0007_remove_exame_paciente_delete_consulta_delete_exame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=200)),
                ('medico', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('ADIADO', 'adiado'), ('EM_ANALISE', 'em_analise')], default='AGENDADO', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('especialidade', models.CharField(max_length=100)),
                ('medico', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('ADIADO', 'adiado'), ('EM_ANALISE', 'em_analise')], default='AGENDADO', max_length=20)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
