# Generated by Django 6.0.7 on 2026-08-21 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pacientes', '0007_remove_exame_paciente_delete_consulta_delete_exame'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True)),
                ('encaminhamento', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento', to='core.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_consulta', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AtendimentoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True)),
                ('encaminhamento', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('exame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento', to='core.exame')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_exame', to='pacientes.paciente')),
            ],
        ),
    ]
