# Generated by Django 6.0.7 on 2026-08-22 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atendimentoconsulta_atendimentoexame'),
        ('gestao_clinica', '0004_medico_exames_horariomedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='tipo_exame',
            field=models.CharField(choices=[('HEMOGRAMA', 'Hemograma'), ('RAIO_X', 'Raio-X'), ('TOMOGRAFIA', 'Tomografia'), ('RESSONANCIA', 'Ressonância'), ('ULTRASSOM', 'Ultrassom'), ('ELETROCARDIOGRAMA', 'Eletrocardiograma')], default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exame',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames_realizados', to='gestao_clinica.medico'),
        ),
    ]
