# Generated by Django 6.0.7 on 2026-08-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exame_tipo_exame_alter_exame_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('CLINICO', 'Clínico Geral'), ('CARDIO', 'Cardiologista'), ('DERMA', 'Dermatologista'), ('PED', 'Pediatra'), ('ORTO', 'Ortopedista'), ('GINE', 'Ginecologista'), ('PSIQ', 'Psiquiatra')], default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
