# Generated by Django 6.0.7 on 2026-08-23 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_consulta_especialidade_consulta_tipo_consulta'),
        ('gestao_clinica', '0009_alter_horariomedico_quantidade_vagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='especialidade',
            field=models.CharField(choices=[('CLINICO', 'Clínico Geral'), ('CARDIO', 'Cardiologista'), ('DERMA', 'Dermatologista'), ('PED', 'Pediatra'), ('ORTO', 'Ortopedista'), ('GINE', 'Ginecologista'), ('PSIQ', 'Psiquiatra')], default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='turno',
            field=models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='gestao_clinica.medico'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='especialidade',
            field=models.CharField(max_length=30),
        ),
    ]
