# Generated by Django 6.0.7 on 2026-08-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consulta_especialidade_consulta_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='turno',
            field=models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exame',
            name='tipo_exame',
            field=models.CharField(choices=[('HEMOGRAMA', 'Hemograma'), ('RAIO_X', 'Raio-X'), ('TOMOGRAFIA', 'Tomografia'), ('ULTRASSOM', 'Ultrassom'), ('ELETROCARDIOGRAMA', 'Eletrocardiograma')], max_length=30),
        ),
    ]
