# Generated by Django 6.0.7 on 2026-09-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exame_turno_alter_exame_tipo_exame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentoexame',
            name='encaminhamento',
        ),
        migrations.RemoveField(
            model_name='atendimentoexame',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='atendimentoconsulta',
            name='conduta',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='atendimentoconsulta',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='atendimentoconsulta',
            name='prescricao',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='atendimentoconsulta',
            name='queixa_principal',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='atendimentoconsulta',
            name='retorno',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='atendimentoconsulta',
            name='sintomas',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='atendimentoexame',
            name='conclusao',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='atendimentoexame',
            name='observacoes_tecnicas',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='atendimentoexame',
            name='resultado',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
