# Generated by Django 6.0.7 on 2026-09-18 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_atendimentoexame_encaminhamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('dosagem', models.CharField(max_length=200)),
                ('frequencia', models.CharField(max_length=200)),
                ('duracao', models.CharField(max_length=200)),
                ('observacoes', models.CharField(blank=True, max_length=500)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='core.atendimentoconsulta')),
            ],
        ),
    ]
