# Generated by Django 6.0.7 on 2026-07-13 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='exame',
            old_name='resultado',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='tratamento',
        ),
        migrations.AddField(
            model_name='consulta',
            name='especialidade',
            field=models.CharField(default='Clínica Geral', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='observacao',
            field=models.TextField(default='vazio', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame',
            name='status',
            field=models.IntegerField(choices=[(1, 'Agendado'), (2, 'Coletado'), (3, 'Em análise'), (4, 'Concluído'), (5, 'Cancelado')], default=1),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default=0, max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
