# Generated by Django 6.0.7 on 2026-07-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_rename_resultado_exame_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
