# Generated by Django 6.0.7 on 2026-07-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='observacao',
        ),
    ]
