# Generated by Django 6.0.7 on 2026-08-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_remove_consulta_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('ADIADO', 'adiado'), ('EM_ANALISE', 'em_analise')], default='AGENDADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='exame',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('ADIADO', 'adiado'), ('EM_ANALISE', 'em_analise')], default='AGENDADO', max_length=20),
        ),
    ]
