# Generated by Django 6.0.7 on 2026-08-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_consulta_status_alter_exame_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Exame',
        ),
    ]
