# Generated by Django 6.0.7 on 2026-08-18 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clinica', '0001_initial'),
        ('pacientes', '0007_remove_exame_paciente_delete_consulta_delete_exame'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atendimento',
            new_name='GestaoDeAtendimento',
        ),
        migrations.AlterField(
            model_name='configuracaovagas',
            name='quantidade_vagas',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
