# Generated by Django 6.0.7 on 2026-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clinica', '0002_rename_atendimento_gestaodeatendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='nome',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
