# Generated by Django 6.0.7 on 2026-08-22 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clinica', '0003_medico_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='exames',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='HorarioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gestao_clinica.medico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('medico', 'dia', 'turno'), name='unique_medico_dia_turno')],
            },
        ),
    ]
