# Generated by Django 6.0.7 on 2026-08-23 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clinica', '0004_medico_exames_horariomedico'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracaovagas',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='configuracaovagas',
            name='medico',
        ),
        migrations.RemoveConstraint(
            model_name='horariomedico',
            name='unique_medico_dia_turno',
        ),
        migrations.AddField(
            model_name='horariomedico',
            name='especialidade',
            field=models.CharField(choices=[('CLINICO', 'Clínico Geral'), ('CARDIO', 'Cardiologista'), ('DERMA', 'Dermatologista'), ('PED', 'Pediatra'), ('ORTO', 'Ortopedista'), ('GINE', 'Ginecologista'), ('PSIQ', 'Psiquiatra')], default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariomedico',
            name='quantidade_vagas',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='horariomedico',
            constraint=models.UniqueConstraint(fields=('medico', 'dia', 'turno', 'especialidade'), name='unique_medico_dia_turno'),
        ),
        migrations.DeleteModel(
            name='ConfiguracaoVagas',
        ),
    ]
