# Generated by Django 6.0.7 on 2026-08-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clinica', '0005_alter_configuracaovagas_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariomedico',
            name='tipo_exame',
            field=models.CharField(blank=True, choices=[('HEMOGRAMA', 'Hemograma'), ('RAIO_X', 'Raio-X'), ('TOMOGRAFIA', 'Tomografia'), ('RESSONANCIA', 'Ressonância'), ('ULTRASSOM', 'Ultrassom'), ('ELETROCARDIOGRAMA', 'Eletrocardiograma')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horariomedico',
            name='especialidade',
            field=models.CharField(blank=True, choices=[('CLINICO', 'Clínico Geral'), ('CARDIO', 'Cardiologista'), ('DERMA', 'Dermatologista'), ('PED', 'Pediatra'), ('ORTO', 'Ortopedista'), ('GINE', 'Ginecologista'), ('PSIQ', 'Psiquiatra')], max_length=20, null=True),
        ),
    ]
