# Generated by Django 6.0.7 on 2026-08-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clinica', '0006_horariomedico_tipo_exame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='email',
            field=models.CharField(default=' ', max_length=11),
            preserve_default=False,
        ),
    ]
