# Generated by Django 6.0.7 on 2026-08-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clinica', '0007_medico_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
