# Generated by Django 6.0.7 on 2026-08-23 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clinica', '0008_alter_medico_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariomedico',
            name='quantidade_vagas',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
