# Generated by Django 6.0.7 on 2026-08-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clinica', '0009_alter_horariomedico_quantidade_vagas'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='horariomedico',
            name='unique_medico_dia_turno',
        ),
        migrations.AddField(
            model_name='horariomedico',
            name='tipo_consulta',
            field=models.CharField(blank=True, choices=[('CLINICO', 'Clínico Geral'), ('CARDIO', 'Cardiologista'), ('DERMA', 'Dermatologista'), ('PED', 'Pediatra'), ('ORTO', 'Ortopedista'), ('GINE', 'Ginecologista'), ('PSIQ', 'Psiquiatra')], max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='horariomedico',
            constraint=models.UniqueConstraint(fields=('medico', 'dia', 'turno', 'especialidade', 'tipo_consulta', 'tipo_exame'), name='unique_medico_dia_turno_tipo'),
        ),
    ]
