# Generated by Django 6.0.7 on 2026-08-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_clinica', '0010_remove_horariomedico_unique_medico_dia_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariomedico',
            name='tipo_exame',
            field=models.CharField(blank=True, choices=[('HEMOGRAMA', 'Hemograma'), ('RAIO_X', 'Raio-X'), ('TOMOGRAFIA', 'Tomografia'), ('ULTRASSOM', 'Ultrassom'), ('ELETROCARDIOGRAMA', 'Eletrocardiograma')], max_length=30, null=True),
        ),
    ]
