# Generated by Django 6.0.7 on 2026-08-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exames',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='exames',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Exames',
        ),
    ]
